name: flora

services:
  kurrentdb:
    image: docker.kurrent.io/kurrent-latest/kurrentdb:26.1.1
    environment:
      KURRENTDB_CLUSTER_SIZE: "1"
      KURRENTDB_RUN_PROJECTIONS: "All"
      KURRENTDB_START_STANDARD_PROJECTIONS: "true"
      KURRENTDB_NODE_PORT: "2113"
      KURRENTDB_INSECURE: "true"
      KURRENTDB_ENABLE_ATOM_PUB_OVER_HTTP: "true"
    ports:
      - "2113:2113"
    volumes:
      - kurrentdb-data:/var/lib/kurrentdb
      - kurrentdb-logs:/var/log/kurrentdb

  xtdb:
    image: ghcr.io/xtdb/xtdb:2.1.0
    ports:
      - "5432:5432"
      - "8080:8080"
    volumes:
      - xtdb-data:/var/lib/xtdb

  nats:
    image: nats:2.12.15-linux
    command: ["-js", "-sd", "/data"]
    ports:
      - "4222:4222"
    volumes:
      - nats-data:/data

  qdrant:
    image: qdrant/qdrant:v1.18.3
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage

volumes:
  kurrentdb-data:
  kurrentdb-logs:
  xtdb-data:
  nats-data:
  qdrant-data:
