"""Synthetic source-selection/provider-contract regressions, not benchmark evidence."""
import asyncio
from dataclasses import replace
import json
from types import SimpleNamespace
import unittest

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat

from flora.comparator import (
    Ed25519TransportObservationVerifier, GeneralMemoryArmAdapter, ProviderRequest,
    encoded, provider_payload, sha,
)
from flora.comparison_run import (
    ArmExecutionFailure, ArmStopped, ExecutionRequest, MeasuredUsage, PreparationRequest, _context_bytes,
)
from flora.selected.comparator_memory import (
    QdrantOriginalMemory, ancestors, lexical_ranking, source_windows, verify_window_context,
)
from comparator_fixtures import (
    FixtureByteCounter, FixtureCompiler, configuration, inputs, signed_response,
)


class ComparatorContractsTest(unittest.IsolatedAsyncioTestCase):
    def setUp(self):
        self.config = configuration()
        self.histories, self.question, self.plan = inputs()
        self.preparation = PreparationRequest("case", "after", self.question, self.histories[("case", "after")], self.plan)
        self.memory = object.__new__(QdrantOriginalMemory)
        self.memory.configuration, self.memory.run_id = self.config, "run"
        self.windows = source_windows(self.preparation.history, self.config)
        self.context = self.memory._context(self.preparation, tuple(range(len(self.windows))), self.windows)
        history = self.preparation.history
        self.execution = ExecutionRequest("case", "after", self.question, history.scope, history.digest(),
            history.event_ids, self.context, self.plan.arm_bindings["general_model_memory"], self.plan)
        self.key = Ed25519PrivateKey.generate()
        self.verifier = Ed25519TransportObservationVerifier(configuration=self.config.provider,
            public_key=self.key.public_key().public_bytes(Encoding.Raw, PublicFormat.Raw))

    def test_windows_bind_actual_unicode_byte_offsets(self):
        source = self.preparation.history.sources[0]
        text = "aé日" * 110
        from cognitive_kernel.experience import ExperienceEvent
        from flora.comparison_run import SourceMaterial, HistorySnapshot
        event = source.event
        # Replace via factory to preserve the canonical event/content digest contract.
        event = replace(event, content_digest=sha(text.encode()))
        # Dataclass event ID is content-addressed and must be regenerated by its factory.
        event = ExperienceEvent.create(event_type=event.event_type, scope=event.scope, occurred_at=event.occurred_at,
            content_digest=event.content_digest, provenance=event.provenance, retention_class=event.retention_class,
            storage_tier=event.storage_tier, parent_event_ids=(), payload_reference=event.payload_reference)
        history = HistorySnapshot(event.scope, (SourceMaterial(event, text.encode()),))
        windows = source_windows(history, self.config)
        self.assertGreater(len(windows), 1)
        for window, fragment in windows:
            self.assertEqual(text.encode()[window.start_byte:window.end_byte], fragment)

    def test_correction_context_includes_ancestors_and_never_claims_authority(self):
        verify_window_context(self.context, self.preparation.history, self.config)
        self.assertEqual(set(ancestors(self.preparation.history, self.windows[-1][0].event_id)),
                         set(self.preparation.history.event_ids))
        self.assertTrue(all(item.kind == "comparator_original_window" and item.claim_value is None for item in self.context.items))
        correction_only = self.memory._context(self.preparation, (len(self.windows) - 1,), self.windows)
        with self.assertRaisesRegex(ValueError, "ancestor closure"):
            verify_window_context(correction_only, self.preparation.history, self.config)

    def test_changed_excerpt_is_rejected(self):
        changed = replace(self.context, items=(replace(self.context.items[0], content=b"changed"),) + self.context.items[1:])
        with self.assertRaisesRegex(ValueError, "actual original"):
            verify_window_context(changed, self.preparation.history, self.config)

    def test_window_bounds_cannot_exceed_actual_bytes_or_change_frozen_segmentation(self):
        from flora.comparator import encoded
        source = self.preparation.history.sources[0]
        window = self.context.plan.windows[0]
        for start, end, expected in ((0, len(source.plaintext) + 5000, "byte bounds"),
                                     (1, len(source.plaintext), "configured source windows")):
            with self.subTest(start=start, end=end):
                fragment = source.plaintext[start:end]
                forged = replace(window, start_byte=start, end_byte=end, content_sha256=sha(fragment))
                content = json.loads(self.context.items[0].content)
                content.update(start_byte=start, end_byte=end, source_excerpt=fragment.decode())
                changed = replace(self.context,
                    plan=replace(self.context.plan, windows=(forged,) + self.context.plan.windows[1:]),
                    items=(replace(self.context.items[0], content=encoded(content)),) + self.context.items[1:])
                with self.assertRaisesRegex(ValueError, expected):
                    verify_window_context(changed, self.preparation.history, self.config)

    def test_original_only_comparator_refuses_native_internal_control_events(self):
        changed = replace(self.context, items=(replace(self.context.items[0],
            control_event_ids=("internal-native-control",)),) + self.context.items[1:])
        with self.assertRaisesRegex(ValueError, "actual original"):
            verify_window_context(changed, self.preparation.history, self.config)

    def test_lexical_route_finds_exact_terms_and_wire_budget_includes_envelope(self):
        ranked = lexical_ranking(b"concise", self.windows)
        self.assertEqual(self.windows[ranked[0]][0].event_id, self.preparation.history.sources[-1].event.event_id)
        body = provider_payload(self.config, question=self.question, context=self.context,
                                response_token_budget=32, wire_compiler=FixtureCompiler())
        self.assertGreater(FixtureByteCounter().count(body).tokens, sum(len(item.content) for item in self.context.items))

    def test_before_after_and_configuration_use_different_projection_namespace(self):
        self.memory.custody = SimpleNamespace(scope_digest="1" * 64)
        before = replace(self.preparation, phase="before", history=self.histories[("case", "before")])
        self.assertNotEqual(self.memory.collection(before), self.memory.collection(self.preparation))
        old = self.memory.collection(before)
        self.memory.configuration = replace(self.config, system_instruction=b"different frozen config")
        self.assertNotEqual(old, self.memory.collection(before))

    def test_transport_signature_binds_actual_request_response_usage_and_model(self):
        body = provider_payload(self.config, question=self.question, context=self.context,
                                response_token_budget=32, wire_compiler=FixtureCompiler())
        request = ProviderRequest(self.config.provider, body, 32)
        response = signed_response(request, "d" * 64, self.key)
        self.verifier.verify(request=request, response=response)
        self.assertIsNone(response.cost_microunits)
        self.assertIsNone(response.currency)
        with self.assertRaises(InvalidSignature):
            self.verifier.verify(request=request, response=replace(response, input_tokens=response.input_tokens + 1))
        with self.assertRaises(ValueError):
            self.verifier.verify(request=request, response=replace(response, returned_model_id="different-model"))

    def adapter(self, *, call_transfer=True, revoke_after=False, counter=None,
                recorder_error=False, invalid_proof=False, missing_custody=False,
                missing_capture=False, wrong_task_marker=False, client_stop=False,
                capture_allowed=True, client_error=False, changed_returned_usage=False):
        state = {"allowed": True, "calls": 0, "tasks": [], "capture_allowed": capture_allowed,
                 "client_calls": 0, "verified_usage_calls": 0}
        key, config = self.key, self.config
        class Disclosure:
            def authorize(self, **kwargs):
                state["calls"] += 1
                if not state["allowed"]:
                    raise PermissionError("fictional permission revoked")
                return "d" * 64
        class Client:
            configuration = config.provider
            async def generate(self, request, *, authorize_transfer, attempt_sink):
                state["client_calls"] += 1
                marker = authorize_transfer() if call_transfer else "d" * 64
                if wrong_task_marker:
                    marker = "d" * 64
                response = signed_response(request, marker, key)
                if invalid_proof:
                    response = replace(response, proof=b"invalid-proof")
                if not missing_capture:
                    attempt_sink.record(response)
                if changed_returned_usage:
                    response = replace(response, input_tokens=999, proof=b"unsigned")
                    response = replace(response, proof=key.sign(encoded(response.observation())))
                if revoke_after:
                    state["allowed"] = False
                if client_stop:
                    # Deliberately incorrect exception metering must be ignored.
                    raise ArmStopped("unavailable", MeasuredUsage(config.provider.feature_engine_id, 999, 999, 999, 1))
                if client_error:
                    raise client_error("fixture private provider details")
                return response
        class BoundSink:
            def __init__(self, task_id, dispatch):
                self.dispatch, self.response, self.marker = dispatch, None, None
                self.task_id = task_id
            def wrap_authorize_transfer(self, callback):
                def authorize():
                    if self.marker is not None:
                        raise PermissionError("fixture task already dispatched")
                    base = callback()
                    self.marker = sha(encoded({"task_id": self.task_id, "source_marker": base,
                                               "payload_sha256": sha(self.dispatch.payload)}))
                    return self.marker
                return authorize
            def record(self, response):
                self.response = response
            def verify_response(self, response):
                if not state["capture_allowed"]:
                    raise PermissionError("fixture capture permission withdrawn")
                if self.response != response or response.authorization_marker != self.marker:
                    raise ValueError("fixture durable task lacks this exact captured response")
                self_outer.verifier.verify(request=self.dispatch, response=response)
            def verified_usage(self):
                state["verified_usage_calls"] += 1
                if self.response is None:
                    return None
                self.verify_response(self.response)
                return MeasuredUsage(config.provider.feature_engine_id, self.response.input_tokens,
                    self.response.input_tokens, self.response.output_tokens, 1,
                    self.response.cost_microunits, self.response.currency)
        self_outer = self
        class Custody:
            def prepare_task(self, *, task_id, arm, request, provider_request):
                if arm != "general_model_memory":
                    raise AssertionError("fixture custody crossed arm")
                sink = BoundSink(task_id, provider_request)
                state["tasks"].append((task_id, arm, request, provider_request, sink))
                return sink
        class Recorder:
            called = False
            def record(self, **kwargs):
                self.called = True
                if recorder_error:
                    raise recorder_error("fictional private recorder details")
                return "fixture-recorded-contract"
        recorder = Recorder()
        memory = SimpleNamespace(configuration=config)
        adapter = GeneralMemoryArmAdapter(configuration=config, memory=memory,
            tokenizer=counter or FixtureByteCounter(), wire_compiler=FixtureCompiler(), client=Client(),
            exchange_verifier=self.verifier, disclosure=Disclosure(), recorder=recorder,
            attempt_custody=None if missing_custody else Custody(),
            task_id_for=lambda request: "fixture-task:" + request.case_id + ":" + request.phase)
        return adapter, state, recorder

    async def test_adapter_requires_transfer_boundary_callback_and_preserves_unknown_cost(self):
        adapter, state, recorder = self.adapter()
        self.assertEqual(await adapter.execute(self.execution), "fixture-recorded-contract")
        self.assertTrue(recorder.called)
        self.assertEqual(state["calls"], 3)
        adapter, _, recorder = self.adapter(call_transfer=False)
        with self.assertRaisesRegex(ValueError, "transfer-boundary"):
            await adapter.execute(self.execution)
        self.assertFalse(recorder.called)

    async def test_dispatch_requires_exact_task_custody_and_captured_observation(self):
        adapter, state, recorder = self.adapter(missing_custody=True)
        with self.assertRaises(ArmStopped) as stopped:
            await adapter.execute(self.execution)
        self.assertEqual(stopped.exception.status, "unavailable")
        self.assertEqual(state["client_calls"], 0)
        self.assertFalse(state["tasks"])
        self.assertFalse(recorder.called)
        adapter, state, recorder = self.adapter(missing_capture=True)
        with self.assertRaises(ValueError) as stopped:
            await adapter.execute(self.execution)
        self.assertFalse(hasattr(stopped.exception, "usage"))
        self.assertFalse(recorder.called)
        task_id, arm, request, dispatch, sink = state["tasks"][0]
        self.assertIs(request, self.execution)
        self.assertEqual(arm, "general_model_memory")
        self.assertNotEqual(sink.marker, "d" * 64)
        self.assertEqual(task_id, "fixture-task:case:after")

    async def test_source_only_or_other_task_marker_cannot_replay_current_task(self):
        adapter, state, recorder = self.adapter(wrong_task_marker=True)
        with self.assertRaisesRegex(ValueError, "transfer-boundary"):
            await adapter.execute(self.execution)
        self.assertEqual(state["client_calls"], 1)
        self.assertFalse(recorder.called)

    async def test_signed_returned_counters_cannot_replace_actual_captured_usage(self):
        adapter, state, recorder = self.adapter(changed_returned_usage=True)
        with self.assertRaises(ArmExecutionFailure) as stopped:
            await adapter.execute(self.execution)
        self.assertEqual(stopped.exception.status, "invalid_result")
        self.assertNotEqual(stopped.exception.usage.input_tokens, 999)
        self.assertEqual(stopped.exception.usage.output_tokens, 9)
        self.assertFalse(recorder.called)
        adapter, state, recorder = self.adapter(changed_returned_usage=True, missing_capture=True)
        with self.assertRaises(ValueError) as stopped:
            await adapter.execute(self.execution)
        self.assertFalse(hasattr(stopped.exception, "usage"))
        self.assertIsNone(adapter.measured_stop_usage(case_id=self.execution.case_id, phase=self.execution.phase,
            plan_sha256=self.execution.plan.digest(), context_sha256=sha(_context_bytes(self.execution.context))))

    async def test_failure_usage_comes_from_captured_observation_not_client_exception(self):
        adapter, state, recorder = self.adapter(client_stop=True)
        with self.assertRaises(ArmStopped) as stopped:
            await adapter.execute(self.execution)
        self.assertEqual(stopped.exception.status, "unavailable")
        self.assertEqual(stopped.exception.usage.output_tokens, 9)
        self.assertNotEqual(stopped.exception.usage.input_tokens, 999)
        self.assertEqual(state["verified_usage_calls"], 1)
        self.assertFalse(recorder.called)
        for kwargs in ({"missing_capture": True}, {"capture_allowed": False}, {"invalid_proof": True}):
            with self.subTest(kwargs=kwargs):
                adapter, state, recorder = self.adapter(client_stop=True, **kwargs)
                with self.assertRaises(ArmStopped) as stopped:
                    await adapter.execute(self.execution)
                self.assertIsNone(stopped.exception.usage)
                self.assertFalse(recorder.called)

    async def test_observed_usage_survives_non_successful_transport_return(self):
        for error, status in ((ValueError, "invalid_result"), (RuntimeError, "failed")):
            with self.subTest(error=error):
                adapter, state, recorder = self.adapter(client_error=error)
                with self.assertRaises(ArmExecutionFailure) as stopped:
                    await adapter.execute(self.execution)
                self.assertEqual(str(stopped.exception), status)
                self.assertEqual(stopped.exception.usage.output_tokens, 9)
                self.assertFalse(recorder.called)
        adapter, state, recorder = self.adapter(client_error=RuntimeError, missing_capture=True)
        with self.assertRaises(RuntimeError) as stopped:
            await adapter.execute(self.execution)
        self.assertFalse(hasattr(stopped.exception, "usage"))
        self.assertFalse(recorder.called)

    async def test_timeout_and_cancellation_keep_only_exact_cached_verified_stop_usage(self):
        request = self.execution
        keywords = dict(case_id=request.case_id, phase=request.phase, plan_sha256=request.plan.digest(),
                        context_sha256=sha(_context_bytes(request.context)))
        for failure in (TimeoutError, asyncio.CancelledError):
            with self.subTest(failure=failure):
                adapter, state, recorder = self.adapter(client_error=failure)
                with self.assertRaises(failure):
                    await adapter.execute(request)
                before = state["verified_usage_calls"]
                usage = adapter.measured_stop_usage(**keywords)
                self.assertEqual(usage.output_tokens, 9)
                self.assertEqual(state["verified_usage_calls"], before)  # Pure metadata getter.
                for change in ({"phase": "before"}, {"plan_sha256": "f" * 64},
                               {"context_sha256": "a" * 64}, {"case_id": "other"},
                               {"context_sha256": None}):
                    self.assertIsNone(adapter.measured_stop_usage(**(keywords | change)))
                # A later stopped execution cannot borrow the previous row.
                adapter.attempt_custody = None
                with self.assertRaises(ArmStopped):
                    await adapter.execute(request)
                self.assertIsNone(adapter.measured_stop_usage(**keywords))
                self.assertFalse(recorder.called)
        for kwargs in ({"invalid_proof": True}, {"wrong_task_marker": True}, {"missing_capture": True}):
            with self.subTest(kwargs=kwargs):
                adapter, state, recorder = self.adapter(client_error=asyncio.CancelledError, **kwargs)
                with self.assertRaises(asyncio.CancelledError):
                    await adapter.execute(request)
                self.assertIsNone(adapter.measured_stop_usage(**keywords))

    async def test_revocation_during_inference_blocks_recorded_acceptance(self):
        adapter, _, recorder = self.adapter(revoke_after=True)
        with self.assertRaises(ArmStopped) as stopped:
            await adapter.execute(self.execution)
        self.assertEqual(stopped.exception.status, "refused")
        self.assertEqual(stopped.exception.usage.feature_calls, 1)
        self.assertEqual(stopped.exception.usage.output_tokens, 9)
        self.assertGreater(stopped.exception.usage.input_tokens, 0)
        self.assertGreater(stopped.exception.usage.context_tokens, 0)
        self.assertIsNone(stopped.exception.usage.cost_microunits)
        self.assertFalse(recorder.called)

    async def test_only_verified_metering_survives_post_inference_record_failure(self):
        for failure, status in ((ValueError, "invalid_result"), (RuntimeError, "failed")):
            with self.subTest(failure=failure):
                adapter, _, recorder = self.adapter(recorder_error=failure)
                with self.assertRaises(ArmExecutionFailure) as stopped:
                    await adapter.execute(self.execution)
                self.assertEqual(str(stopped.exception), status)
                self.assertEqual(stopped.exception.usage.feature_calls, 1)
                self.assertTrue(recorder.called)
        adapter, _, recorder = self.adapter(revoke_after=True, invalid_proof=True)
        with self.assertRaises(InvalidSignature) as invalid:
            await adapter.execute(self.execution)
        self.assertFalse(hasattr(invalid.exception, "usage"))
        self.assertFalse(recorder.called)

    async def test_actual_request_budget_and_frozen_arm_checked_before_call(self):
        adapter, state, recorder = self.adapter()
        with self.assertRaises(ArmStopped):
            await adapter.execute(replace(self.execution, plan=replace(self.plan, context_token_budget=1)))
        self.assertEqual(state["calls"], 0)
        with self.assertRaisesRegex(ValueError, "frozen arm"):
            await adapter.execute(replace(self.execution, binding=replace(self.execution.binding, lineage_sha256="e" * 64)))
        self.assertFalse(recorder.called)

    async def test_tokenizer_receipt_must_bind_actual_compiled_body(self):
        class WrongCount(FixtureByteCounter):
            def count(self, content):
                return replace(super().count(content), content_sha256="e" * 64)
        adapter, state, recorder = self.adapter(counter=WrongCount())
        with self.assertRaisesRegex(ValueError, "actual input"):
            await adapter.execute(self.execution)
        self.assertEqual(state["calls"], 0)
        self.assertFalse(recorder.called)


if __name__ == "__main__":
    unittest.main()
