"""Synthetic source-selection/provider-contract regressions, not benchmark evidence."""
from dataclasses import replace
import json
from types import SimpleNamespace
import unittest

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat

from flora.comparator import (
    Ed25519TransportObservationVerifier, GeneralMemoryArmAdapter, ProviderRequest,
    provider_payload, sha,
)
from flora.comparison_run import ArmExecutionFailure, ArmStopped, ExecutionRequest, PreparationRequest
from flora.selected.comparator_memory import (
    QdrantOriginalMemory, ancestors, lexical_ranking, source_windows, verify_window_context,
)
from comparator_fixtures import (
    FixtureByteCounter, FixtureCompiler, configuration, inputs, signed_response,
)


class ComparatorContractsTest(unittest.IsolatedAsyncioTestCase):
    def setUp(self):
        self.config = configuration()
        self.histories, self.question, self.plan = inputs()
        self.preparation = PreparationRequest("case", "after", self.question, self.histories[("case", "after")], self.plan)
        self.memory = object.__new__(QdrantOriginalMemory)
        self.memory.configuration, self.memory.run_id = self.config, "run"
        self.windows = source_windows(self.preparation.history, self.config)
        self.context = self.memory._context(self.preparation, tuple(range(len(self.windows))), self.windows)
        history = self.preparation.history
        self.execution = ExecutionRequest("case", "after", self.question, history.scope, history.digest(),
            history.event_ids, self.context, self.plan.arm_bindings["general_model_memory"], self.plan)
        self.key = Ed25519PrivateKey.generate()
        self.verifier = Ed25519TransportObservationVerifier(configuration=self.config.provider,
            public_key=self.key.public_key().public_bytes(Encoding.Raw, PublicFormat.Raw))

    def test_windows_bind_actual_unicode_byte_offsets(self):
        source = self.preparation.history.sources[0]
        text = "aé日" * 110
        from cognitive_kernel.experience import ExperienceEvent
        from flora.comparison_run import SourceMaterial, HistorySnapshot
        event = source.event
        # Replace via factory to preserve the canonical event/content digest contract.
        event = replace(event, content_digest=sha(text.encode()))
        # Dataclass event ID is content-addressed and must be regenerated by its factory.
        event = ExperienceEvent.create(event_type=event.event_type, scope=event.scope, occurred_at=event.occurred_at,
            content_digest=event.content_digest, provenance=event.provenance, retention_class=event.retention_class,
            storage_tier=event.storage_tier, parent_event_ids=(), payload_reference=event.payload_reference)
        history = HistorySnapshot(event.scope, (SourceMaterial(event, text.encode()),))
        windows = source_windows(history, self.config)
        self.assertGreater(len(windows), 1)
        for window, fragment in windows:
            self.assertEqual(text.encode()[window.start_byte:window.end_byte], fragment)

    def test_correction_context_includes_ancestors_and_never_claims_authority(self):
        verify_window_context(self.context, self.preparation.history, self.config)
        self.assertEqual(set(ancestors(self.preparation.history, self.windows[-1][0].event_id)),
                         set(self.preparation.history.event_ids))
        self.assertTrue(all(item.kind == "comparator_original_window" and item.claim_value is None for item in self.context.items))
        correction_only = self.memory._context(self.preparation, (len(self.windows) - 1,), self.windows)
        with self.assertRaisesRegex(ValueError, "ancestor closure"):
            verify_window_context(correction_only, self.preparation.history, self.config)

    def test_changed_excerpt_is_rejected(self):
        changed = replace(self.context, items=(replace(self.context.items[0], content=b"changed"),) + self.context.items[1:])
        with self.assertRaisesRegex(ValueError, "actual original"):
            verify_window_context(changed, self.preparation.history, self.config)

    def test_window_bounds_cannot_exceed_actual_bytes_or_change_frozen_segmentation(self):
        from flora.comparator import encoded
        source = self.preparation.history.sources[0]
        window = self.context.plan.windows[0]
        for start, end, expected in ((0, len(source.plaintext) + 5000, "byte bounds"),
                                     (1, len(source.plaintext), "configured source windows")):
            with self.subTest(start=start, end=end):
                fragment = source.plaintext[start:end]
                forged = replace(window, start_byte=start, end_byte=end, content_sha256=sha(fragment))
                content = json.loads(self.context.items[0].content)
                content.update(start_byte=start, end_byte=end, source_excerpt=fragment.decode())
                changed = replace(self.context,
                    plan=replace(self.context.plan, windows=(forged,) + self.context.plan.windows[1:]),
                    items=(replace(self.context.items[0], content=encoded(content)),) + self.context.items[1:])
                with self.assertRaisesRegex(ValueError, expected):
                    verify_window_context(changed, self.preparation.history, self.config)

    def test_original_only_comparator_refuses_native_internal_control_events(self):
        changed = replace(self.context, items=(replace(self.context.items[0],
            control_event_ids=("internal-native-control",)),) + self.context.items[1:])
        with self.assertRaisesRegex(ValueError, "actual original"):
            verify_window_context(changed, self.preparation.history, self.config)

    def test_lexical_route_finds_exact_terms_and_wire_budget_includes_envelope(self):
        ranked = lexical_ranking(b"concise", self.windows)
        self.assertEqual(self.windows[ranked[0]][0].event_id, self.preparation.history.sources[-1].event.event_id)
        body = provider_payload(self.config, question=self.question, context=self.context,
                                response_token_budget=32, wire_compiler=FixtureCompiler())
        self.assertGreater(FixtureByteCounter().count(body).tokens, sum(len(item.content) for item in self.context.items))

    def test_before_after_and_configuration_use_different_projection_namespace(self):
        self.memory.custody = SimpleNamespace(scope_digest="1" * 64)
        before = replace(self.preparation, phase="before", history=self.histories[("case", "before")])
        self.assertNotEqual(self.memory.collection(before), self.memory.collection(self.preparation))
        old = self.memory.collection(before)
        self.memory.configuration = replace(self.config, system_instruction=b"different frozen config")
        self.assertNotEqual(old, self.memory.collection(before))

    def test_transport_signature_binds_actual_request_response_usage_and_model(self):
        body = provider_payload(self.config, question=self.question, context=self.context,
                                response_token_budget=32, wire_compiler=FixtureCompiler())
        request = ProviderRequest(self.config.provider, body, 32)
        response = signed_response(request, "d" * 64, self.key)
        self.verifier.verify(request=request, response=response)
        self.assertIsNone(response.cost_microunits)
        self.assertIsNone(response.currency)
        with self.assertRaises(InvalidSignature):
            self.verifier.verify(request=request, response=replace(response, input_tokens=response.input_tokens + 1))
        with self.assertRaises(ValueError):
            self.verifier.verify(request=request, response=replace(response, returned_model_id="different-model"))

    def adapter(self, *, call_transfer=True, revoke_after=False, counter=None,
                recorder_error=False, invalid_proof=False):
        state = {"allowed": True, "calls": 0}
        key, config = self.key, self.config
        class Disclosure:
            def authorize(self, **kwargs):
                state["calls"] += 1
                if not state["allowed"]:
                    raise PermissionError("fictional permission revoked")
                return "d" * 64
        class Client:
            configuration = config.provider
            async def generate(self, request, *, authorize_transfer):
                marker = authorize_transfer() if call_transfer else "d" * 64
                response = signed_response(request, marker, key)
                if invalid_proof:
                    response = replace(response, proof=b"invalid-proof")
                if revoke_after:
                    state["allowed"] = False
                return response
        class Recorder:
            called = False
            def record(self, **kwargs):
                self.called = True
                if recorder_error:
                    raise recorder_error("fictional private recorder details")
                return "fixture-recorded-contract"
        recorder = Recorder()
        memory = SimpleNamespace(configuration=config)
        adapter = GeneralMemoryArmAdapter(configuration=config, memory=memory,
            tokenizer=counter or FixtureByteCounter(), wire_compiler=FixtureCompiler(), client=Client(),
            exchange_verifier=self.verifier, disclosure=Disclosure(), recorder=recorder)
        return adapter, state, recorder

    async def test_adapter_requires_transfer_boundary_callback_and_preserves_unknown_cost(self):
        adapter, state, recorder = self.adapter()
        self.assertEqual(await adapter.execute(self.execution), "fixture-recorded-contract")
        self.assertTrue(recorder.called)
        self.assertEqual(state["calls"], 3)
        adapter, _, recorder = self.adapter(call_transfer=False)
        with self.assertRaisesRegex(ValueError, "transfer-boundary"):
            await adapter.execute(self.execution)
        self.assertFalse(recorder.called)

    async def test_revocation_during_inference_blocks_recorded_acceptance(self):
        adapter, _, recorder = self.adapter(revoke_after=True)
        with self.assertRaises(ArmStopped) as stopped:
            await adapter.execute(self.execution)
        self.assertEqual(stopped.exception.status, "refused")
        self.assertEqual(stopped.exception.usage.feature_calls, 1)
        self.assertEqual(stopped.exception.usage.output_tokens, 9)
        self.assertGreater(stopped.exception.usage.input_tokens, 0)
        self.assertGreater(stopped.exception.usage.context_tokens, 0)
        self.assertIsNone(stopped.exception.usage.cost_microunits)
        self.assertFalse(recorder.called)

    async def test_only_verified_metering_survives_post_inference_record_failure(self):
        for failure, status in ((ValueError, "invalid_result"), (RuntimeError, "failed")):
            with self.subTest(failure=failure):
                adapter, _, recorder = self.adapter(recorder_error=failure)
                with self.assertRaises(ArmExecutionFailure) as stopped:
                    await adapter.execute(self.execution)
                self.assertEqual(str(stopped.exception), status)
                self.assertEqual(stopped.exception.usage.feature_calls, 1)
                self.assertTrue(recorder.called)
        adapter, _, recorder = self.adapter(revoke_after=True, invalid_proof=True)
        with self.assertRaises(InvalidSignature) as invalid:
            await adapter.execute(self.execution)
        self.assertFalse(hasattr(invalid.exception, "usage"))
        self.assertFalse(recorder.called)

    async def test_actual_request_budget_and_frozen_arm_checked_before_call(self):
        adapter, state, recorder = self.adapter()
        with self.assertRaises(ArmStopped):
            await adapter.execute(replace(self.execution, plan=replace(self.plan, context_token_budget=1)))
        self.assertEqual(state["calls"], 0)
        with self.assertRaisesRegex(ValueError, "frozen arm"):
            await adapter.execute(replace(self.execution, binding=replace(self.execution.binding, lineage_sha256="e" * 64)))
        self.assertFalse(recorder.called)

    async def test_tokenizer_receipt_must_bind_actual_compiled_body(self):
        class WrongCount(FixtureByteCounter):
            def count(self, content):
                return replace(super().count(content), content_sha256="e" * 64)
        adapter, state, recorder = self.adapter(counter=WrongCount())
        with self.assertRaisesRegex(ValueError, "actual input"):
            await adapter.execute(self.execution)
        self.assertEqual(state["calls"], 0)
        self.assertFalse(recorder.called)


if __name__ == "__main__":
    unittest.main()
